### UPLOAD ATTACH
POST http://localhost:8080/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="image.png"

< C:\Users\User\Downloads\image.png
###

### OPEN ATTACH
GET http://localhost:8080/attach/open/8229eef5-a571-4cee-9066-7164886e7095.png
###